CREATE TABLE USERS
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    ROLES INT,
    LAST_LOGIN TIMESTAMP,
    VERIFIED INT


);

CREATE TABLE ROLES
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(32) NOT NULL,
    MASK INT NOT NULL
);

CREATE TABLE USER_ROLE_ASSIGNMENT
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT REFERENCES USERS(ID),
    ROLES_ID INT REFERENCES ROLES(ID)
);

CREATE TABLE CONTENT
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CREATED_BY INT REFERENCES USERS(ID),
    VISIBLE_AT INT,
    TITLE VARCHAR(32),
    LONG_DESC VARCHAR(1024),
    CREATED_AT BIGINT,
    LAST_UPDATED BIGINT
);